### ISSUE TITLE
[Suggestion] Backport to other main release minecraft versions affected.

### ISSUE THREAD

**Issue by thecatcore** [MikolajKolek/fix-alt-gr#1]

**Comment by MikolajKolek** [comment]
OK, I will have to check what older versions are affected, and I'll try to port to them as long as they are supported by Fabric (so potentially versions from 1.14 to 1.17)

**Comment by MikolajKolek** [comment]
The backport to 1.14 - 1.17 has been completed in the [1.14-1.16](https://github.com/MikolajKolek/fix-alt-gr/tree/1.14-1.16) and [1.17](https://github.com/MikolajKolek/fix-alt-gr/tree/1.17) branches, and all the builds are available for download on [Modrinth](https://modrinth.com/mod/fix-alt-gr/versions).

**Comment by thecatcore** [comment]
Awesome 🤩!!
