### ISSUE TITLE
1.19 fabric or forge?

### ISSUE THREAD

**Issue by VileSmith** [MikolajKolek/fix-alt-gr#2]
when?

**Comment by MikolajKolek** [comment]
First of all, if you're using fabric, you should be able to painlessly switch to quilt, as in my experience it works really well and it's very stable, and all the fabric mods I've tried work. 
As for the fabric or forge versions, of course if you comply with the licence, you or anyone else is free to port the mod to those loaders, but I currently have no plans to support them myself on 1.19.
