### ISSUE TITLE
Fabric 1.20.1 support

### ISSUE THREAD

**Issue by Hunter99011** [MikolajKolek/fix-alt-gr#4]
Hi,

will the mod support Fabric 1.20.1?

I tried to load it on the latest versions, since its sadly still affected by the Alt gr bug, but it won't load.

**Comment by MikolajKolek** [comment]
I currently have no plans of making fix-alt-gr work with Fabric. You can use [Quilt](https://quiltmc.org/en/) instead, it supports (pretty much) all Fabric mods, and it works perfectly well with 1.20.1.

**Comment by Hunter99011** [comment]
It supports pretty much of the mods, but for example I'm building with Axiom and nowadays Axiom is pretty common in use for the building community, which isn't supported by Quilt because Axiom is waiting on a feature fabric implemented years ago, but Quilt didn't. Plus I have plenty other mods that don't support Quilt, so a switch isn't possible for most of the people I would say.

It's sad that this isn't available for fabric after 1.18.2.

**Comment by Hunter99011** [comment]
Since I work with Axiom and FAWE for building, I use long commands with #simplex[] for example and much more patterns, and when Alt + Gr lock in, I usually clear all the command what I just wrote, sometimes 200 characters long and I just want to scream so much.

**Comment by MikolajKolek** [comment]
Alright, at the time I was switching to Quilt it looked like a good plan, but looking at the situation of Fabric mods unsupported on Quilt as you outline it, it probably is a good idea to switch back. I'll try to get this done, but unfortunately I don't have the time for it at the moment - you'll probably need to wait around two weeks for it. 

In the meantime, there is actually a way to get Axiom running on Quilt - it only requires a bit of hackery. You need to open the Axiom jar in any program for opening zip files (like 7zip or WinRAR) and then delete the `org/lwjgl` folder. Once this is done, it should just start working on Quilt (or at least it did for me)

**Comment by MikolajKolek** [comment]
I have ported the mod to Farbric 1.21, and will soon backport to Fabric 1.19 - 1.20. I'm sorry that it took this long, but I hope that resolves your issue!
